apiVersion: v1
kind: Service
metadata:
  name: helloworld-spring-svc
  labels:
    app: helloworld-spring
    version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
      app: helloworld-spring
      version: {{ .Chart.AppVersion }}
