apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-spring
  labels:
    app: helloworld-spring
    version: {{ .Chart.AppVersion }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.helloworld.ingress }}
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: helloworld-spring-svc
              port:
                number: 80
