#
# Build the project

name: Build

#
# Operational Variables

env:
  MAJOR: 0
  MINOR: 0

#
# Establish when the workflow is run
# We do build on every push except when we push onto main (which ought to be subject to branch protection)
# We do build whenever a PR onto main is closed (see on) and the code is actually merged (see release job if)
# Why is that okay?
# Since we're making a PR, we know from the previous workflow run on push that the repo is okay and the PR
# shows that to us. A PR itself doesn't cause a build, except when it is closed and the changes were merged.

on:
  push:
    branches-ignore:
    - main
  pull_request_target:
    branches:
    - main
    types:
    - closed

#
# Workflow

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Calculate Build Context
      run: |
        MRMAT_VERSION="${MAJOR}.${MINOR}.${GITHUB_RUN_NUMBER}"
        if [ "$GITHUB_EVENT_NAME" == 'pull_request_target' -a "$GITHUB_BASE_REF" == 'main' ]; then
          MRMAT_IS_RELEASE=true
          echo "::warning ::Building release ${MRMAT_VERSION}"
          echo "MRMAT_IS_RELEASE=true" >> $GITHUB_ENV
        else
          MRMAT_VERSION="${MRMAT_VERSION}-SNAPSHOT"
          echo "::warning ::Building version ${MRMAT_VERSION}"
        fi
        echo "MRMAT_VERSION=${MRMAT_VERSION}" >> $GITHUB_ENV

    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build
      run: ./gradlew build

    # Modifies the SARIF output produced by Detekt so that absolute URIs are relative
    # This is so we can easily map results onto their source files
    # This can be removed once relative URI support lands in Detekt: https://git.io/JLBbA
#    - name: Make artifact location URIs relative
#      continue-on-error: true
#      run: |
#        echo "$(
#          jq \
#            --arg github_workspace ${{ github.workspace }} \
#            '. | ( .runs[].results[].locations[].physicalLocation.artifactLocation.uri |= if test($github_workspace) then .[($github_workspace | length | . + 1):] else . end )' \
#            ${{ github.workspace }}/detekt.sarif.json
#        )" > ${{ github.workspace }}/detekt.sarif.json

    # Uploads results to GitHub repository using the upload-sarif action
    - uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: ${{ github.workspace }}/build/reports/detekt/detekt.sarif
        checkout_path: ${{ github.workspace }}

    - name: Upload build reports
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: build/reports

    - name: Conditional Release
      uses: marvinpinto/action-automatic-releases@latest
      if: (github.event.pull_request.merged == true && github.base_ref == 'main')
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.MRMAT_VERSION }}"
        prerelease: false
        title: "Release ${{ env.MRMAT_VERSION }}"
